services:
  bitaxe-benchmark:
    build:
      context: .
      args:
        BASE_PATH: /bitaxe
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - results:/results
      - config:/config
    networks:
      - proxy

volumes:
  results:
  config:

networks:
  proxy:
    external: true
